---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Cancer genome standards for long-read sequencing using cancer cell line mixtures

## Summary

This repository hosts the analysis scripts and pipeline associated with the paper in submission.

In this study, we evaluated the performance of long-read sequencing (LRS) for detecting somatic variants across a range of tumor purities and sequencing depths, comparing results to short-read sequencing. We generated 22 whole-genome sequencing datasets from controlled mixtures of cancer and matched normal cell lines (0%–100% tumor purity). This design enabled benchmarking of LRS-based somatic variant detection under realistic scenarios.

## Table of Contents

### Raw data processing

 - [Base calling and read alignment for cell line mixtures](1.dna_mixing_celllines/nanopore_paired_tumour_workflow/README.md##Base calling and read alignment)
 - [Sequencing depth combinations](2.simulate_sequencing_depth/README.md)
 - [Variant calling](1.dna_mixing_celllines/nanopore_paired_tumour_workflow/README.md##Variant calling)
 - [Variant merging and benchmarking]()
 - [QC and purity check](1.dna_mixing_celllines/R_analysis/0.purity_and_qc.md): Rmd file [purity_and_qc.Rmd](1.dna_mixing_celllines/R_analysis/0.purity_and_qc.Rmd)
 
### Downstream analysis and plots

 - [Construct gold standard](1.dna_mixing_celllines/R_analysis/x.gold_standard.md): Rmd file [gold_standard.Rmd](1.dna_mixing_celllines/R_analysis/x.gold_standard.Rmd)
 - [Tumour purity affects SNV and indel calling](1.dna_mixing_celllines/R_analysis/1.benchmark_snv_calling.md): Rmd file [benchmark_snv_calling.Rmd](1.dna_mixing_celllines/R_analysis/1.benchmark_snv_calling.Rmd)
 - [Tumour purity affects SV calling](1.dna_mixing_celllines/R_analysis/3.benchmark_sv_calling.md): Rmd file [benchmark_sv_calling.Rmd](1.dna_mixing_celllines/R_analysis/3.benchmark_sv_calling.md)
 - [Sequencing depth affects SNV and indel calling](2.simulate_sequencing_depth/R_analysis/1.benchmark_snv_calling.md): Rmd file [benchmark_snv_calling.Rmd](2.simulate_sequencing_depth/R_analysis/1.benchmark_snv_calling.Rmd)
 - [Sequencing depth affects SV calling](2.simulate_sequencing_depth/R_analysis/2.benchmark_sv_calling.md): Rmd file [benchmark_sv_calling.Rmd](2.simulate_sequencing_depth/R_analysis/2.benchmark_sv_calling.Rmd)
 - [Mutational signature analysis](1.dna_mixing_celllines/R_analysis/1.snv_mutational_signature.md): Rmd file [snv_mutational_signature.Rmd](1.dna_mixing_celllines/R_analysis/1.snv_mutational_signature.Rmd)
 - [Genomic regions of false positive calls](1.dna_mixing_celllines/R_analysis/4.genome_regions.md): Rmd file [genome_regions.Rmd](1.dna_mixing_celllines/R_analysis/4.genome_regions.Rmd)
 - [Germline leakage](3.igv_check/R_analysis/germline_leakage.md): Rmd file [germline_leakage.Rmd](3.igv_check/R_analysis/germline_leakage.Rmd)
 - [SV type and length in LR](3.igv_check/R_analysis/lr_unique_sv_length_type.md): Rmd file [lr_unique_length_type.Rmd](3.igv_check/R_analysis/lr_unique_sv_length_type.Rmd)

### Miscellaneous

 - [Sequencing depth check](2.simulate_sequencing_depth/R_analysis/0.depth_check.md): Rmd file [depth_check.Rmd](2.simulate_sequencing_depth/R_analysis/0.depth_check.Rmd)
 - [Methylation analysis](1.dna_mixing_celllines/R_analysis/2.methylation_analysis.md): Rmd file [methylation_analysis.Rmd](1.dna_mixing_celllines/R_analysis/2.methylation_analysis.Rmd)
 - [Cicos plot](3.igv_check/R_analysis/0.circos_plots.md): Rmd file [circos_plots.Rmd](3.igv_check/R_analysis/0.circos_plots.Rmd)
 - [IGV check](3.igv_check/README.md)
 
## License

This project is licensed under the MIT License. See the [LICENSE](LICENSE) file for details.