---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(ggpubfigs)
library(introdataviz)
colorblind_pals <- friendly_pals$contrast_three
names(colorblind_pals) <- c("01","10","11")

#sv_palette = c( "DEL"="#BC4749","INS/DUP"="#F4ACB7","INV"="#588157","TRA" = "#FF9F1C")
sv_palette = c( "DEL"="#0081a7","INS/DUP"="#F4ACB7","INV"="#588157","TRA" = "#FF9F1C")
suppvec_labeller <- c("11"= "TP (Concordant)", "01" = "FP (LR unique)", "10"="FN (SR unique)")
knitr::opts_chunk$set(root.dir = here(), comment = NA, echo = FALSE, message = FALSE, warnings = FALSE, include = TRUE, fig.align = 'center',fig.retina=2)
```


With the hypothesis that unique SVs detected by long reads are potentially real, I investigate the type and length distribution of those SVs.

```{r, fig.width=5.8, fig.height=3}
df_lr_unique <- list.files("../lr_specific/bedpe", pattern="all.bedpe", full.names = TRUE) |> discard(\(x) grepl("_\\d+",x)) |> 
  set_names(\(f) basename(f) |> str_split_i("\\.",1)) |> 
  map(\(f) read_tsv(f,col_names = c("chrom1","pos1","chrom2","pos2","svtype","svlen","suppvec"))) |> 
  list_rbind(names_to = "celltype") |> mutate(svtype=ifelse(svtype %in% c("DUP","INS"), "INS/DUP", svtype), svlen=ifelse(svtype=="TRA", 0, svlen), svlen=abs(svlen))

df_lr_unique |> ggplot(aes(x=svtype, fill=svtype)) + geom_bar() + facet_grid(celltype~suppvec, scales = "free_y", labeller = labeller(suppvec=suppvec_labeller)) + scale_fill_manual(values = sv_palette) + theme_bw() +
  theme(strip.background = element_rect(fill="white"), axis.text.x = element_text(size=8), legend.position = "bottom") + labs(x="", y="Number of SVs", fill="")

ggsave("figures/figure5b.pdf", width = 5.8, height = 3,dpi = "retina")
```

There are most DEL and INS/DUP identified by LR.

```{r, warning=FALSE,fig.width=6, fig.height=4.2}
df_lr_unique |> filter(svtype!="TRA") |> group_by(svtype,suppvec) |> 
  summarise(meanlen=median(svlen)) |> knitr::kable() 

df_lr_unique |> filter(svtype!="TRA", suppvec!="10") |> ggplot(aes(x=svtype, y=svlen, fill=suppvec)) + 
  geom_split_violin(alpha=.5, size=.2) + scale_y_log10(labels=c("100bp","1Kbp","10Kbp","100Kbp","1Mbp","10Mbp"), breaks=c(1e+2,1e+3, 1e+4, 1e+5,1e+6,1e+7)) +
  facet_grid(~celltype, scales = "free_y") + scale_fill_manual(values=colorblind_pals, labels=suppvec_labeller) +
  geom_boxplot(width = .2, alpha = .8,show.legend = FALSE, fatten=NULL, outlier.size = .5) +
  stat_summary(fun.data = "mean_se", geom = "pointrange", show.legend = F, position = position_dodge(.175), size=.5) +
  theme_bw() +
  theme(strip.background = element_rect(fill="white"), legend.position =  "bottom") + labs(x="", y="SV length", fill="")

ggsave("figures/figure5c.pdf", width = 6, height = 4.2,dpi = "retina")
```